apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-replicationcontroller
spec:
  replicas: 3
  template:
    metadata:
      name: tomcat-replicationcontroller
      labels:
       app: tomcatapp
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.0
        ports:
        - containerPort: 7474
